<?xml version="1.0" encoding="utf-8"?>
<report>
	<activity
		result="Failed"
		duration="7618ms"
		durationms="7618"
		type="root"
		rid="78d3d290630a65b"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		user="pandey"
		host="FLR1622"
		rxversion="5.4.6.0"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		language="en-US"
		screenresolution="3200x1080"
		timestamp="6/28/2016 4:31:13 PM"
		timestampiso="2016-06-28T14:31:13"
		timeoutfactor="1">
		<detail>
			Ranorex Testscript
		</detail>
		<item
			timeRelativeToTestSuiteStartTime="00:00.204"
			timeRelativeToTestModuleStartTime="00:00.204"
			timeWallClock="16:31:14"
			time="00:00.204"
			level="Failure"
			category="TestSuite">
			<message>
				Thread was being aborted.
			</message>
			<metainfo
				stacktrace="   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at Ranorex.Controls.ProgressForm.Show()
   at Ranorex.Core.Testing.TestSuiteRunner.RunInternal(Type containerType, String testSuiteXml, RunParams rp)"
				loglvl="Failure"/>
		</item>
		<item
			timeRelativeToTestSuiteStartTime="00:07.618"
			timeRelativeToTestModuleStartTime="00:07.618"
			timeWallClock="16:31:21"
			time="00:07.618"
			level="Error"
			category="Module">
			<message>
				Test run was aborted by the user.
			</message>
			<metainfo
				loglvl="Error"/>
		</item>
	</activity>
</report>
